<a href="https://colab.research.google.com/github/bharathbolla/END-NLP/blob/Session-4/END%2BEVA6_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch
import torchvision # provide access to datasets, models, transforms, utils, etc
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

from torchvision import datasets, transforms

In [ ]:
class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.conv1 = nn.Conv2d(1,32, 3,padding=0,bias=False )
    self.conv2 = nn.Conv2d(32,16, 3,padding=0,bias=False )
    self.conv3 = nn.Conv2d(16, 8,3, padding=0, bias=False)
    self.linear1 = nn.Linear(200, 16)
    self.linear2 = nn.Linear(16,10)
    self.flatten = nn.Flatten()

  def forward(self, X):
    X = F.relu(self.conv1(X))
    X = F.relu(self.conv2(X))
    X = F.max_pool2d(X, 2)
    X = F.relu(self.conv3(X))
    X = F.max_pool2d(X, 2)
    X = self.flatten(X)
    X = F.relu(self.linear1(X))
    X = self.linear2(X)
    return F.log_softmax(X)


In [ ]:
# importing the required libraries
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
  
# defining the Dataset class
class data_set(Dataset):
    def __init__(self):
      super(Dataset, self).__init__()
      rand_numbers = torch.randint(0, 9, (60000,), dtype = torch.int8 )
      self.data = rand_numbers
  
    def __len__(self):
        return len(self.data)
  
    def __getitem__(self, index):
        return self.data[index]
  
  
dataset = data_set()
  
# implementing dataloader on the dataset and printing per batch
dataloader = DataLoader(dataset,  batch_size=32, shuffle=True)
for i, batch in enumerate(dataloader):
    print(i, batch)

0 tensor([3, 5, 6, 7, 0, 4, 8, 3, 3, 2, 7, 6, 4, 8, 2, 1, 8, 4, 0, 5, 7, 1, 3, 4,
        5, 4, 7, 5, 3, 5, 2, 3], dtype=torch.int8)
1 tensor([4, 3, 6, 8, 1, 2, 3, 5, 8, 6, 4, 2, 1, 3, 4, 5, 8, 8, 6, 6, 5, 1, 2, 2,
        7, 8, 1, 0, 5, 2, 8, 4], dtype=torch.int8)
2 tensor([2, 8, 1, 0, 3, 3, 7, 8, 2, 7, 3, 1, 6, 8, 8, 7, 6, 0, 2, 5, 8, 5, 1, 7,
        0, 0, 5, 7, 0, 2, 1, 2], dtype=torch.int8)
3 tensor([3, 8, 5, 8, 7, 3, 4, 2, 5, 6, 7, 0, 6, 8, 2, 2, 0, 7, 8, 1, 7, 1, 0, 7,
        6, 1, 1, 1, 0, 8, 3, 6], dtype=torch.int8)
4 tensor([1, 5, 1, 4, 1, 6, 3, 8, 8, 8, 2, 5, 0, 6, 0, 5, 0, 0, 5, 0, 5, 1, 3, 5,
        4, 8, 1, 4, 5, 0, 8, 1], dtype=torch.int8)
5 tensor([5, 0, 2, 3, 1, 6, 6, 3, 6, 4, 0, 8, 7, 0, 5, 0, 7, 4, 7, 6, 0, 6, 7, 1,
        5, 5, 3, 6, 1, 5, 1, 1], dtype=torch.int8)
6 tensor([4, 5, 6, 0, 5, 5, 4, 0, 0, 3, 6, 7, 6, 5, 3, 0, 1, 4, 0, 4, 1, 1, 4, 3,
        5, 7, 4, 1, 0, 8, 1, 5], dtype=torch.int8)
7 tensor([6, 5, 5, 7, 7, 7, 5, 5, 1, 4, 5, 1, 4, 4, 2, 8, 2, 3, 8, 6,

In [ ]:
dataloader = DataLoader(dataset, shuffle=True)
train_loader = torch.utils.data.DataLoader( 
    datasets.MNIST('../data', train=True, download=True,
                    transform=transforms.Compose([
                        transforms.RandomRotation((-7.0, 7.0), fill=(1,)),
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ])),
    batch_size=1, shuffle=True)

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting ../data/MNIST/raw/train-images-idx3-ubyte.gz to ../data/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting ../data/MNIST/raw/train-labels-idx1-ubyte.gz to ../data/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting ../data/MNIST/raw/t10k-images-idx3-ubyte.gz to ../data/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting ../data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../data/MNIST/raw

Processing...
Done!


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [ ]:
tensor_mnist_train = datasets.MNIST('../data', train=True, download=True,
                    transform=transforms.Compose([
                        transforms.RandomRotation((-7.0, 7.0), fill=(1,)),
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ]))

In [ ]:
data_path = '/content/mnist'
tensor_mnist_train = datasets.MNIST(data_path, train=True, download = True)


Extracting /content/mnist/MNIST/raw/train-images-idx3-ubyte.gz to /content/mnist/MNIST/raw




Extracting /content/mnist/MNIST/raw/train-labels-idx1-ubyte.gz to /content/mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /content/mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to /content/mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /content/mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to /content/mnist/MNIST/raw

Processing...
Done!


In [ ]:
print(len(train_loader))


60000


In [ ]:
randint_train = torch.randint(0, 9, (60000,), dtype = torch.int8 )
print(randint_train.shape)
print(type(randint_train[0]))

torch.Size([60000])
<class 'torch.Tensor'>


In [ ]:
tensor_sum = []
for i  in range (len(tensor_mnist_train)):
  img, label = tensor_mnist_train[i]
  tensor_sum.append(randint_train[i] + label)
  if i == 1 or i % 5000 == 0:
    print(label, randint_train[i], tensor_sum[i])

5 tensor(7, dtype=torch.int8) tensor(12, dtype=torch.int8)
0 tensor(5, dtype=torch.int8) tensor(5, dtype=torch.int8)
7 tensor(3, dtype=torch.int8) tensor(10, dtype=torch.int8)
3 tensor(5, dtype=torch.int8) tensor(8, dtype=torch.int8)
5 tensor(7, dtype=torch.int8) tensor(12, dtype=torch.int8)
5 tensor(3, dtype=torch.int8) tensor(8, dtype=torch.int8)
3 tensor(8, dtype=torch.int8) tensor(11, dtype=torch.int8)
3 tensor(6, dtype=torch.int8) tensor(9, dtype=torch.int8)
1 tensor(4, dtype=torch.int8) tensor(5, dtype=torch.int8)
7 tensor(8, dtype=torch.int8) tensor(15, dtype=torch.int8)
3 tensor(7, dtype=torch.int8) tensor(10, dtype=torch.int8)
3 tensor(5, dtype=torch.int8) tensor(8, dtype=torch.int8)
1 tensor(2, dtype=torch.int8) tensor(3, dtype=torch.int8)


In [ ]:
# importing the required libraries
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
  
# defining the Dataset class
class TS_Data_set(Dataset):
    def __init__(self):
      super(Dataset, self).__init__()
      #tensor_sum = torch.randint(0, 9, (60000,), dtype = torch.int8 )
      self.data = tensor_sum
  
    def __len__(self):
        return len(self.data)
  
    def __getitem__(self, index):
        return self.data[index]
  
  
tensor_sum_data = TS_Data_set()

In [ ]:
# importing the required libraries
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
  
# defining the Dataset class
class Rand_Int(Dataset):
    def __init__(self):
      super(Dataset, self).__init__()
      #tensor_sum = torch.randint(0, 9, (60000,), dtype = torch.int8 )
      self.data = randint_train
  
    def __len__(self):
        return len(self.data)
  
    def __getitem__(self, index):
        return self.data[index]
  
  
rand_int_data = Rand_Int()
  


In [ ]:
img_50, label_50 = tensor_mnist_train[50]
print(rand_int_data[50], label_50, tensor_sum_data[50])


tensor(4, dtype=torch.int8) 3 tensor(7, dtype=torch.int8)


In [ ]:
print(len(tensor_sum_data), len(rand_int_data))

60000 60000


In [ ]:
tensor_sum_data[0]

tensor(12, dtype=torch.int8)

In [ ]:
dataloaders1 = DataLoader(datasets.MNIST('../data', train=True, download=True,
                    transform=transforms.Compose([
                        transforms.RandomRotation((-7.0, 7.0), fill=(1,)),
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ])), batch_size=1, shuffle=False)
dataloaders2 = DataLoader(rand_int_data, batch_size=1, shuffle=False)
dataloaders3 = DataLoader(tensor_sum_data, batch_size=1, shuffle=False)



In [ ]:
for i, (mnist_d, randint, sumint) in enumerate(zip(dataloaders1, dataloaders2, dataloaders3)):
    if i % 10000==0:
      data, target = mnist_d
      print(randint,target, sumint)

tensor([7], dtype=torch.int8) tensor([5]) tensor([12], dtype=torch.int8)
tensor([5], dtype=torch.int8) tensor([3]) tensor([8], dtype=torch.int8)
tensor([3], dtype=torch.int8) tensor([5]) tensor([8], dtype=torch.int8)
tensor([6], dtype=torch.int8) tensor([3]) tensor([9], dtype=torch.int8)
tensor([8], dtype=torch.int8) tensor([7]) tensor([15], dtype=torch.int8)
tensor([5], dtype=torch.int8) tensor([3]) tensor([8], dtype=torch.int8)


## Combined Data Set


In [ ]:

# Create a class to combine MNIST dataset and random numbers between 0 and 9
class Combined_Dataset():

  # We pass the train variable to get train or test data, and batch_size
  def __init__(self, train, batch_size):

      self.batch_size = batch_size
      # Load the MNIST data into the data_loader object
      self.data_loader = torch.utils.data.DataLoader(
          torchvision.datasets.MNIST('/files/', train=train, download=True,
                                transform=torchvision.transforms.Compose([
                                  torchvision.transforms.ToTensor(),
                                  torchvision.transforms.Normalize(
                                    (0.1307,), (0.3081,))
                                ])),
          batch_size=self.batch_size, shuffle=True)

      # Number of samples in the dataaset
      self.dataset = self.data_loader.dataset            

  # getitem function creats batches of our dataset on the fly by calling next(iter())
  def __getitem__(self, index):
      # Extract one batch of the MNIST data_loader
      image, label = next(iter(self.data_loader))

      # Generate randoms numbers between 0 and 9 of size=batch_size. The datatype is float as this is the input required for the network
      random_numbers = torch.tensor([randint(0,9) for _ in range(self.batch_size)], dtype=torch.float32)

      # Combine inputs and outputs as a list after transfering the tensors to the GPU
      x = [image.to(device), cat_array(random_numbers).to(device)]
      # y labels for addition of number is reshaped to [32,1] as MSE requires it in this format
      y = [label.to(device), (label+random_numbers).reshape([32,1]).to(device)]

      return x, y

  def __len__(self):
      return len(self.data_loader)

# Set the batch size
batch_size = 32

# Create the train and test dataset
train_data = Combined_Dataset(train=True, batch_size=batch_size)
test_data = Combined_Dataset(train=False, batch_size=batch_size)

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /files/MNIST/raw/train-images-idx3-ubyte.gz to /files/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /files/MNIST/raw/train-labels-idx1-ubyte.gz to /files/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /files/MNIST/raw/t10k-images-idx3-ubyte.gz to /files/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /files/MNIST/raw/t10k-labels-idx1-ubyte.gz to /files/MNIST/raw

Processing...
Done!


In [ ]:
type(train_data)

__main__.Combined_Dataset

TypeError: ignored

In [ ]:

     
class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.conv1 = nn.Conv2d(1,32, 3,padding=0,bias=False )
    self.conv2 = nn.Conv2d(32,16, 3,padding=0,bias=False )
    self.conv3 = nn.Conv2d(16, 8,3, padding=0, bias=False)
    self.linear1 = nn.Linear(200, 16)
    self.linear2 = nn.Linear(16,10)
    self.linear3 = nn.Linear(20,10)
    self.flatten = nn.Flatten()

  def forward(self, X, Y):
    X = F.relu(self.conv1(X))
    X = F.relu(self.conv2(X))
    X = F.max_pool2d(X, 2)
    X = F.relu(self.conv3(X))
    X = F.max_pool2d(X, 2)
    X = self.flatten(X)
    X = F.relu(self.linear1(X))
    X = self.linear2(X)
    print("X shape before X1 squeeze", X.shape)
    X1 =  torch.squeeze(X)
    print("X1 shape after X1 squeeze", X.shape)
    #Y = to_categorical(Y)
    print("Y Shape", Y.shape)
    Y = torch.cat((X1,Y)) # This will result in 20 dimensions
    #Y = Y.to(device)
    Y = self.linear3(Y)
    print("Shape of X", X.shape)
    print("Shape of Y", Y.shape)
    #output1 = F.log_softmax(X)
    print("oUTPUT1 sHAPE", output1.shape)
    output2 = torch.unsqueeze(Y,0)
    #output2 = F.log_softmax(output2)
    print("Output2 Shape", output2.shape)
    return output1, output2


In [ ]:
!pip install torchsummary

In [ ]:
!export CUDA_LAUNCH_BLOCKING=1

In [ ]:
# Setting up the device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Assuming that we are on a CUDA machine, this should print a CUDA device:
print("The device available is: ", device)

The device available is:  cuda:0


In [ ]:
# Create an object of the class Network and transfer it to the GPU
model = Model().to(device)
print(" The model layers are: ")
print(model)

print("\nShape of parameters in each layer is: ")
for name, param in model.named_parameters():
    print(name, '\t\t', param.shape)

# Selecting the loss function and optimizer  for the model
CE_loss = nn.CrossEntropyLoss()
MSE_loss = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

RuntimeError: ignored

In [ ]:
for epoch in range(10):  # Loop over the dataset multiple times

    total_loss = 0.0
    total_correct_1, total_correct_2 = 0, 0
    # Loop over the entire length of train data
    for i in range(len(train_data)):
        # Get the inputs and outputs
        # Input data x is a list of [images, random numbers], output data y is a list of [classes, sum of numbers]
        x, y = next(iter(train_data))

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward + Backward + Optimize
        output1, output2 = model(x[0], x[1])
        # Use the CE loss for classification and MSE loss for addition 
        loss = CE_loss(output1, y[0]) + MSE_loss(output2, y[1])
        loss.backward()
        optimizer.step()

        # Calculate statistics
        total_loss += loss.item()
        total_correct_1 += output1.argmax(dim=1).eq(y[0]).sum().item()
        total_correct_2 += (torch.round(output2) == torch.round(y[1])).sum().item()
        
    # Print statistics        
    print(f"Epoch: {epoch+1}, loss: {total_loss}, Classification Acc: {100 * (total_correct_1/(len(train_data.dataset)))}, Addition Acc: {100 * (total_correct_2/(len(train_data.dataset)))}")
    
print('Finished Training')

In [ ]:
for epoch in range(10):  # Loop over the dataset multiple times

    total_loss = 0.0
    total_correct_1, total_correct_2 = 0, 0
    # Loop over the entire length of train data
    for i, (mnist_d, randint, sumint) in enumerate(zip(dataloaders1, dataloaders2, dataloaders3)):
      data, target = mnist_d
    
     
      #target = to_categorical(target)
      #target = torch.unsqueeze(target,0)
      #sumint = to_categorical(sumint)
      sumint, randint = sumint.to(device), randint.to(device)
      data, target = data.to(device), target.to(device)
      print("This is target",target)
      # Zero the parameter gradients
      optimizer.zero_grad()

      # Forward + Backward + Optimize
      output1, output2 = model(data, randint)
      print("Traget shape", target.shape)
      print("Sumint Shape", sumint.shape)
      # Use the CE loss for classification and MSE loss for addition 
      loss = CE_loss(output1,target) + CE_loss(output2, sumint.long())
      print("Sumint Tensor", sumint.long())
      #loss2 = F.nll_loss(output2, sumint.long())
      #loss = loss1 + loss2
      loss.backward()
      optimizer.step()

      # Calculate statistics
      total_loss += loss.item()
      total_correct_1 += output1.argmax(dim=1).eq(target).sum().item()
      #total_correct_2 += (torch.round(output2) == torch.round(y[1])).sum().item()
      total_correct_1 += output2.argmax(dim=1).eq(sumint).sum().item()
        
    # Print statistics        
    print(f"Epoch: {epoch+1}, loss: {total_loss}, Classification Acc: {100 * (total_correct_1/(60000))}, Addition Acc: {100 * (total_correct_2/(60000))}")
    
print('Finished Training')     

       

This is target tensor([5], device='cuda:0')
X shape after X1 squeeze torch.Size([1, 10])
X shape after X1 squeeze torch.Size([1, 10])
Y Shape torch.Size([10])
Shape of X torch.Size([1, 10])
Shape of Y torch.Size([10])
oUTPUT1 sHAPE torch.Size([1, 10])
Output2 Shape torch.Size([1, 10])
Traget shape torch.Size([1])
Sumint Shape torch.Size([1])
Sumint Tensor 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:38: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


RuntimeError: ignored

In [ ]:
def to_categorical(y,num_classes=10):
    """ 1-hot encodes a tensor """
    return torch.from_numpy(np.eye(num_classes, dtype='uint8')[y])

In [ ]:
torch.tensor([1]).long()

tensor([1])

In [ ]:
from tqdm import tqdm

train_losses = []
test_losses = []
train_acc = []
test_acc = []

def train(model, device, train_loader, optimizer, epoch):
  model.train()
  pbar = tqdm(train_loader)
  correct = 0
  processed = 0
  for batch_idx, (data, target) in enumerate(pbar):
    # get samples
    data, target = data.to(device), target.to(device)

    # Init
    optimizer.zero_grad()
    # In PyTorch, we need to set the gradients to zero before starting to do backpropragation because PyTorch accumulates the gradients on subsequent backward passes. 
    # Because of this, when you start your training loop, ideally you should zero out the gradients so that you do the parameter update correctly.

    # Predict
    y_pred = model(data)

    # Calculate loss
    loss = F.nll_loss(y_pred, target)
    train_losses.append(loss)

    # Backpropagation
    loss.backward()
    optimizer.step()

    # Update pbar-tqdm
    
    pred = y_pred.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
    correct += pred.eq(target.view_as(pred)).sum().item()
    processed += len(data)

    pbar.set_description(desc= f'Loss={loss.item()} Batch_id={batch_idx} Accuracy={100*correct/processed:0.2f}')
    train_acc.append(100*correct/processed)


In [ ]:
import numpy as np
torch.cat((to_categorical(5), to_categorical(2))).shape

torch.Size([20])

In [ ]:
to_categorical(5)

RuntimeError: ignored

In [ ]:
to_categorical(0)

RuntimeError: ignored

In [ ]:
torch.stack((to_categorical(5), to_categorical(2)), 1)

tensor([[0, 0],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], device='cuda:0', dtype=torch.uint8)

In [ ]:
1+2

3

In [ ]:
def to_categorical(y,num_classes=10):
    """ 1-hot encodes a tensor """
    return (np.eye(num_classes, dtype='uint8')[y])

In [ ]:
vf = np.vectorize(to_categorical)

In [ ]:
x= np.array([1,2])
x

array([1, 2])

In [ ]:
def cat_array(x):
    return torch.from_numpy(np.array([to_categorical(xi) for xi in x]) )


In [ ]:
cat= cat_array(x)
cat

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.uint8)

In [ ]:
cat.shape

torch.Size([2, 10])